export const DEFAULT_WORK_MINUTES = 25;
export const DEFAULT_SHORT_BREAK_MINUTES = 5;
export const DEFAULT_LONG_BREAK_MINUTES = 15;
export const DEFAULT_SESSIONS_BEFORE_LONG_BREAK = 4;
export const FREE_TIER_MAX_TASKS = 10;
export const FOCUS_SCORE_PENALTY = 15;
